import React, { PropsWithChildren } from 'react';
import Head from 'next/head';
export default function Dashboard({ children }: PropsWithChildren) {
	return (
		<>
			<Head>
				<title>Chris Tam</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
				<link rel="apple-touch-icon" href="/favicon.ico" />
				<link rel="manifest" href="/manifest.json" />
				<meta name="description" content="Chris Tam personal website" />
				<meta property="og:type" content="website" />
				<meta property="og:title" content="Chris Tam" />
				<meta property="og:description" content="Chris Tam personal website" />
				<meta property="og:site_name" content="Chris Tam" />
				<meta property="twitter:card" content="Chris Tam" />
				<meta property="twitter:creator" content="Chris Tam" />
				<meta property="twitter:title" content="Chris Tam" />
				<meta
					property="twitter:description"
					content="Chris Tam personal website"
				/>
			</Head>
			<div>{children}</div>
		</>
	);
}
